#
# Makefile for SpeechOutNot
#
# George Ferguson, ferguson@cs.rochester.edu, 11 Sep 2002
# $Id: Makefile,v 1.2 2007/06/21 12:46:16 wdebeaum Exp $
#

MAIN	= SpeechOutNot
PACKAGE = TRIPS.SpeechOutNot
CLASS   = SpeechOutNot
USES    = TRIPS.TripsModule TRIPS.KQML

SRCS = SpeechOutNot.java
CLASSES = $(SRCS:.java=.class)

CONFIGDIR=../config
include $(CONFIGDIR)/java/prog.mk
