#
# Makefile for TRIPS IM
#
# George Ferguson, ferguson@cs.rochester.edu, 20 Sep 2003
# Time-stamp: <Fri Sep 16 12:27:54 EDT 2011 jallen>
#

NAME = BASICDIALOGUEAGENT
DEFSYS = defsys.lisp
SYSTEM = :dagent

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk

