# To create a new module, the NAME= and SYSTEM = need to be
# changed appropriately.  DEFSYS, CONFIGDIR, and include should 
# not be modified.

NAME = Dummy
DEFSYS = defsys.lisp
SYSTEM = :dummy

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk

